/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IvlaunchInterface extends ethers.utils.Interface {
  functions: {
    "buyAndClaimTickets(tuple,bytes)": FunctionFragment;
    "transfer(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "buyAndClaimTickets",
    values: [
      { owner: string; tickets: BigNumberish; validity: BigNumberish },
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "buyAndClaimTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;

  events: {};
}

export class Ivlaunch extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IvlaunchInterface;

  functions: {
    buyAndClaimTickets(
      info_: { owner: string; tickets: BigNumberish; validity: BigNumberish },
      sig_: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "buyAndClaimTickets((address,uint256,uint256),bytes)"(
      info_: { owner: string; tickets: BigNumberish; validity: BigNumberish },
      sig_: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    transfer(
      to: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transfer(address,uint256)"(
      to: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  buyAndClaimTickets(
    info_: { owner: string; tickets: BigNumberish; validity: BigNumberish },
    sig_: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "buyAndClaimTickets((address,uint256,uint256),bytes)"(
    info_: { owner: string; tickets: BigNumberish; validity: BigNumberish },
    sig_: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  transfer(
    to: string,
    value: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transfer(address,uint256)"(
    to: string,
    value: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    buyAndClaimTickets(
      info_: { owner: string; tickets: BigNumberish; validity: BigNumberish },
      sig_: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "buyAndClaimTickets((address,uint256,uint256),bytes)"(
      info_: { owner: string; tickets: BigNumberish; validity: BigNumberish },
      sig_: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    transfer(
      to: string,
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "transfer(address,uint256)"(
      to: string,
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    buyAndClaimTickets(
      info_: { owner: string; tickets: BigNumberish; validity: BigNumberish },
      sig_: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "buyAndClaimTickets((address,uint256,uint256),bytes)"(
      info_: { owner: string; tickets: BigNumberish; validity: BigNumberish },
      sig_: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    transfer(
      to: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transfer(address,uint256)"(
      to: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    buyAndClaimTickets(
      info_: { owner: string; tickets: BigNumberish; validity: BigNumberish },
      sig_: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "buyAndClaimTickets((address,uint256,uint256),bytes)"(
      info_: { owner: string; tickets: BigNumberish; validity: BigNumberish },
      sig_: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    transfer(
      to: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transfer(address,uint256)"(
      to: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
